#!/bin/sh

# Copyright © 2016-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

orig_ssh_add=$(command -v -p ssh-add) || {
    printf 'ssh-add: command not found\n' >&2
    exit 127
}

if [ $# != 0 ]
then
    exec "$orig_ssh_add" "$@"
fi

for pubkey in ~/.ssh/*.pub
do
    seckey="${pubkey%.pub}.gpg"
    [ -e "$seckey" ] || continue
    gpg -q -d < "$seckey" | "$orig_ssh_add" -
done

# vim:ts=4 sts=4 sw=4 et
