#!/bin/sh

# Copyright © 2016-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# != 0 ]
then
    exec /usr/bin/ssh-add "$@"
fi

for pubkey in ~/.ssh/*.pub
do
    seckey="${pubkey%.pub}.gpg"
    [ -e "$seckey" ] || continue
    gpg -q -d < "$seckey" | /usr/bin/ssh-add /dev/stdin
done

# vim:ts=4 sts=4 sw=4 et
